import { useEffect, useMemo, useState } from "react";
import { MapPin } from "lucide-react";
import MapClickSelector from "../map/components/MapClickSelector";

interface Street { name: string; latitude: number; longitude: number }
interface Props { address: string; latitude?: number; longitude?: number; onChange(value:{address:string;latitude?:number;longitude?:number}):void }

export default function MissionLocationField({address,latitude,longitude,onChange}:Props) {
  const [streets,setStreets]=useState<Street[]>([]); const [mapOpen,setMapOpen]=useState(false); const [listOpen,setListOpen]=useState(false);
  useEffect(()=>{fetch("/data/montrottier/roads.geojson").then(response=>response.json()).then((data)=>{const byName=new Map<string,Street>();for(const feature of data.features??[]){const name=String(feature.properties?.name??"").trim();const coordinates=feature.geometry?.type==="LineString"?feature.geometry.coordinates:feature.geometry?.type==="MultiLineString"?feature.geometry.coordinates.flat():[];if(!name||!coordinates.length||byName.has(name))continue;const middle=coordinates[Math.floor(coordinates.length/2)];byName.set(name,{name,longitude:Number(middle[0]),latitude:Number(middle[1])});}setStreets([...byName.values()].sort((a,b)=>a.name.localeCompare(b.name,"fr")));}).catch(()=>setStreets([]));},[]);
  const selected=useMemo(()=>streets.find(street=>street.name===address),[address,streets]);
  const filtered=useMemo(()=>{const query=address.trim().toLocaleLowerCase("fr-FR");return streets.filter(street=>!query||street.name.toLocaleLowerCase("fr-FR").includes(query));},[address,streets]);
  const chooseAddress=(value:string)=>{const street=streets.find(item=>item.name===value);onChange({address:value,latitude:street?.latitude??latitude,longitude:street?.longitude??longitude});};
  const chooseMap=(nextLatitude:number,nextLongitude:number)=>{const nearest=streets.reduce<Street|undefined>((best,street)=>!best||distance(street,nextLatitude,nextLongitude)<distance(best,nextLatitude,nextLongitude)?street:best,undefined);onChange({address:nearest?.name??`${nextLatitude.toFixed(6)}, ${nextLongitude.toFixed(6)}`,latitude:nextLatitude,longitude:nextLongitude});};
  return <div className="mission-location-field"><label>Adresse de la mission — rues de Montrottier<div className="street-picker"><input required value={address} onFocus={()=>setListOpen(true)} onChange={event=>{chooseAddress(event.target.value);setListOpen(true);}} onBlur={()=>window.setTimeout(()=>{setListOpen(false);if(address&&!streets.some(street=>street.name===address))onChange({address:"",latitude:undefined,longitude:undefined});},150)} placeholder="Cliquez pour afficher les rues…" autoComplete="off"/>{listOpen&&<div className="street-suggestions" role="listbox">{filtered.length?<><small>{filtered.length} voie(s) trouvée(s)</small>{filtered.map(street=><button type="button" role="option" aria-selected={street.name===address} key={street.name} onMouseDown={event=>{event.preventDefault();chooseAddress(street.name);setListOpen(false);}}><MapPin/>{street.name}</button>)}</>:<p>Aucune rue de Montrottier ne correspond.</p>}</div>}</div></label><button type="button" className="secondary-button" onClick={()=>setMapOpen(value=>!value)}><MapPin/> {mapOpen?"Masquer la carte":"Choisir directement sur la carte"}</button>{selected&&<small>Rue sélectionnée : {selected.name}</small>}{mapOpen&&<MapClickSelector latitude={latitude??45.7907} longitude={longitude??4.4668} title={address||"Emplacement de la mission"} height={300} onChange={chooseMap}/>}</div>;
}

function distance(street:Street,latitude:number,longitude:number){return (street.latitude-latitude)**2+(street.longitude-longitude)**2;}
