import { useMemo, useState } from "react";
import { Archive, Download, FileJson, Map, MoreVertical, Plus, Printer, Route, Upload } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import { useIdentity } from "../../access/LocalIdentityProvider";
import { dossierActivityRepository } from "../../dossiers/services/dossierActivityRepository";
import { makeId, missionRepository } from "../../field/repository";
import type { Mission } from "../../field/types";
import CommuneMap from "../../map/components/CommuneMap";
import { useCustomMapLayers } from "../../map/hooks/useCustomMapLayers";
import { exportLayerCsv, exportLayerGeoJson, printLayer } from "../../map/services/businessLayerExport";
import { inspectGeoJson, type GeoJsonCandidate } from "../../map/services/geoJsonImport";
import { routingConfiguration, routingErrorMessage } from "../../map/services/roadRouting";
import { calculateLineLength } from "../../map/services/customLayerStorage";
import { BUSINESS_KIND_LABELS, BUSINESS_LAYER_KINDS, STATUS_LABELS, type CustomMapLayerKind, type CustomMapLayerStatus, type InterventionSide } from "../../map/types/customLayer";

const formatMeters = (value: number) => `${Math.round(value).toLocaleString("fr-FR")} m`;
const blankLayerForm = () => ({ name: `Éparage ${new Date().getFullYear()}`, kind: "eparage" as CustomMapLayerKind, year: new Date().getFullYear(), description: "", color: "#d97706", active: true, archived: false });

export default function BusinessLayersPage() {
  const { user, can } = useIdentity();
  const store = useCustomMapLayers(user.id);
  const [params, setParams] = useSearchParams();
  const [showArchived, setShowArchived] = useState(false);
  const availableLayers = store.layers.filter((item) => !item.deletedAt && (showArchived || !item.archived));
  const selectedId = params.get("layer") ?? availableLayers[0]?.id ?? "";
  const layer = availableLayers.find((item) => item.id === selectedId) ?? availableLayers[0];
  const sections = store.sections.filter((section) => section.layerId === layer?.id);
  const canCreate = can("carte", "create");
  const canEdit = can("carte", "update");
  const canDelete = can("carte", "delete");
  const [actionMenu, setActionMenu] = useState(false);
  const [modal, setModal] = useState<"create" | "edit" | "duplicate" | "delete" | null>(null);
  const [layerForm, setLayerForm] = useState(blankLayerForm);
  const [copySections, setCopySections] = useState(false);
  const [deleteConfirmation, setDeleteConfirmation] = useState("");
  const [drawing, setDrawing] = useState<Array<[number, number]>>([]);
  const [drawingMode, setDrawingMode] = useState<"choice" | "free" | "automatic" | null>(null);
  const [routePoints, setRoutePoints] = useState<Array<[number, number]>>([]);
  const [routeDistance, setRouteDistance] = useState<number | null>(null);
  const [routing, setRouting] = useState(false);
  const [routingError, setRoutingError] = useState("");
  const [sectionForm, setSectionForm] = useState({ name: "", sector: "", side: "deux-cotes" as InterventionSide, status: "a-faire" as CustomMapLayerStatus, completionDate: "", notes: "", dossierId: "" });
  const [importCandidates, setImportCandidates] = useState<GeoJsonCandidate[]>([]);
  const [importSummary, setImportSummary] = useState<{ total: number; ignored: number } | null>(null);
  const totals = useMemo(() => ({ count: sections.length, roads: sections.reduce((sum, section) => sum + section.lengthMeters, 0), todo: sections.filter((section) => section.status !== "realise").reduce((sum, section) => sum + section.businessLengthMeters, 0), done: sections.filter((section) => section.status === "realise").reduce((sum, section) => sum + section.businessLengthMeters, 0), all: sections.reduce((sum, section) => sum + section.businessLengthMeters, 0) }), [sections]);
  const impact = useMemo(() => {
    const missions = new Set(sections.map((section) => section.missionId).filter(Boolean));
    const dossiers = new Set(sections.map((section) => section.dossierId).filter((id): id is number => id !== undefined));
    for (const mission of missionRepository.list()) if (missions.has(mission.id) && mission.dossierId) dossiers.add(mission.dossierId);
    return { portions: sections.length, missions: missions.size, dossiers: dossiers.size, history: layer?.history.length ?? 0 };
  }, [layer, sections]);

  const selectLayer = (id: string) => setParams(id ? { layer: id } : {});
  const logLinkedDossiers = (label: string) => {
    const dossierIds = new Set(sections.map((section) => section.dossierId).filter((id): id is number => id !== undefined));
    dossierIds.forEach((dossierId) => dossierActivityRepository.add({ dossierId, type: "dossier", action: "business-layer-updated", label, authorId: user.id }));
  };
  const openCreate = () => { setLayerForm(blankLayerForm()); setModal("create"); };
  const openEdit = () => { if (!layer) return; setLayerForm({ name: layer.name, kind: layer.kind, year: layer.year ?? new Date().getFullYear(), description: layer.description, color: layer.color, active: layer.active, archived: layer.archived }); setModal("edit"); setActionMenu(false); };
  const openDuplicate = () => { if (!layer) return; setLayerForm({ name: `${layer.name} — copie`, kind: layer.kind, year: layer.year ?? new Date().getFullYear(), description: layer.description, color: layer.color, active: true, archived: false }); setCopySections(false); setModal("duplicate"); setActionMenu(false); };
  const submitLayer = (event: React.FormEvent) => {
    event.preventDefault();
    if (modal === "create") { const created = store.addLayer(layerForm); selectLayer(created.id); }
    if (modal === "edit" && layer) { store.updateLayer(layer.id, layerForm); logLinkedDossiers(`${user.firstName} a modifié la couche métier « ${layerForm.name} »`); }
    if (modal === "duplicate" && layer) { const created = store.duplicateLayer(layer.id, { name: layerForm.name, copySections }); if (created) selectLayer(created.id); }
    setModal(null);
  };
  const toggleArchive = () => {
    if (!layer) return;
    const nextArchived = !layer.archived;
    if (nextArchived && !window.confirm(`Archiver « ${layer.name} » ? Les ${sections.length} portion(s) et tout l’historique seront conservés.`)) return;
    store.setLayerArchived(layer.id, nextArchived);
    logLinkedDossiers(`${user.firstName} a ${nextArchived ? "archivé" : "réactivé"} la couche métier « ${layer.name} »`);
    setActionMenu(false);
    if (nextArchived && !showArchived) selectLayer(store.layers.find((item) => item.id !== layer.id && !item.archived && !item.deletedAt)?.id ?? "");
  };
  const openDelete = () => { setDeleteConfirmation(""); setModal("delete"); setActionMenu(false); };
  const confirmDelete = () => {
    if (!layer || deleteConfirmation !== layer.name) return;
    if (store.deleteLayer(layer.id)) { setModal(null); selectLayer(store.layers.find((item) => item.id !== layer.id && !item.archived && !item.deletedAt)?.id ?? ""); }
  };
  const resetDrawing = () => { setDrawing([]); setRoutePoints([]); setRouteDistance(null); setRoutingError(""); };
  const closeDrawing = () => { resetDrawing(); setDrawingMode(null); };
  const calculateRoute = async () => {
    if (routePoints.length < 2) return;
    if (!routingConfiguration.provider) { setRoutingError(routingConfiguration.message); return; }
    setRouting(true); setRoutingError(""); setDrawing([]);
    try {
      const result = await routingConfiguration.provider.route({ points: routePoints, profile: "driving" });
      setDrawing(result.geometry.coordinates.map(([longitude, latitude]) => [latitude, longitude]));
      setRouteDistance(result.distanceMeters);
    } catch (error) { setRoutingError(routingErrorMessage(error)); }
    finally { setRouting(false); }
  };
  const saveSection = (event: React.FormEvent) => { event.preventDefault(); if (!layer || drawing.length < 2) return; store.addSection({ layerId: layer.id, name: sectionForm.name, sector: sectionForm.sector, status: sectionForm.status, completionDate: sectionForm.completionDate, notes: sectionForm.notes, interventionSide: sectionForm.side, dossierId: sectionForm.dossierId ? Number(sectionForm.dossierId) : undefined, geometry: { type: "LineString", coordinates: drawing.map(([lat, lon]) => [lon, lat]) }, source: drawingMode === "automatic" ? "routing" : "manual" }); closeDrawing(); setSectionForm({ ...sectionForm, name: "", sector: "", notes: "" }); };
  const createMission = (sectionId: string) => { const section = sections.find((item) => item.id === sectionId); if (!section || !layer) return; const now = new Date().toISOString(); const first = section.geometry.coordinates[0]; const mission: Mission = { id: makeId("mission"), title: `${BUSINESS_KIND_LABELS[layer.kind]} — ${section.name}`, description: `Intervention issue de la couche ${layer.name}. ${section.notes}`.trim(), address: [section.name, section.sector].filter(Boolean).join(" · "), longitude: first[0], latitude: first[1], priority: "Normale", status: "À faire", dueDate: "", category: "Voirie", dossierId: section.dossierId, assigneeIds: ["u-tech"], attachments: [], reports: [], history: [{ id: makeId("history"), at: now, userId: user.id, label: `Mission créée depuis la portion ${section.name}` }], createdAt: now, updatedAt: now }; missionRepository.save([mission, ...missionRepository.list()]); store.updateSection(section.id, { missionId: mission.id }); if (section.dossierId) dossierActivityRepository.add({ dossierId: section.dossierId, type: "mission", action: "created", label: `${user.firstName} a créé la mission ${mission.title} depuis ${layer.name}`, authorId: user.id, missionId: mission.id, timestamp: now }); window.alert("Mission créée et préremplie."); };
  const readImport = async (file?: File) => { if (!file) return; try { const summary = inspectGeoJson(await file.text()); setImportCandidates(summary.candidates.slice(0, 500)); setImportSummary({ total: summary.totalFeatures, ignored: summary.ignored }); } catch { window.alert("Ce fichier GeoJSON n’est pas valide."); } };
  const importSelected = () => { if (!layer) return; importCandidates.filter((candidate) => candidate.selected).forEach((candidate) => store.addSection({ layerId: layer.id, name: candidate.name, status: "a-faire", interventionSide: "gauche", geometry: candidate.geometry, source: "uMap", sourceProperties: candidate.properties })); setImportCandidates([]); setImportSummary(null); };
  const changeStatus = (sectionId: string, status: CustomMapLayerStatus) => { const section = sections.find((item) => item.id === sectionId); if (!section) return; const completionDate = status === "realise" ? new Date().toISOString().slice(0, 10) : section.completionDate; store.updateSection(section.id, { status, completionDate }); if (section.dossierId) dossierActivityRepository.add({ dossierId: section.dossierId, type: "dossier", action: "business-layer-status", label: `${user.firstName} a passé « ${section.name} » à ${STATUS_LABELS[status]} dans ${layer?.name ?? "une couche métier"}`, authorId: user.id, timestamp: new Date().toISOString() }); };

  return <section className="business-layers-page">
    <div className="page-heading"><div><span className="eyebrow">Voirie · campagnes</span><h2>Couches métier / portions de voirie</h2><p>Tracez, mesurez et suivez les interventions linéaires de la commune.</p></div>{canCreate && <button className="primary-button" onClick={openCreate}><Plus size={18} /> Nouvelle couche</button>}</div>
    <div className="business-layer-toolbar">
      <label>Campagne<select value={layer?.id ?? ""} onChange={(event) => selectLayer(event.target.value)}>{availableLayers.map((item) => <option key={item.id} value={item.id}>{item.name}{item.archived ? " (archivée)" : ""}</option>)}</select></label>
      <label className="archive-filter"><input type="checkbox" checked={showArchived} onChange={(event) => setShowArchived(event.target.checked)} /> Afficher les archives</label>
      {layer && <><button className="secondary-button" onClick={() => exportLayerCsv(layer, sections)}><Download size={16} /> CSV</button><button className="secondary-button" onClick={() => exportLayerGeoJson(layer, sections)}><FileJson size={16} /> GeoJSON</button><button className="secondary-button" onClick={() => printLayer(layer)}><Printer size={16} /> Imprimer / PDF</button>{canCreate && !layer.archived && <label className="secondary-button file-button"><Upload size={16} /> Import ciblé<input type="file" accept=".geojson,.json,application/geo+json" onChange={(event) => readImport(event.target.files?.[0])} /></label>}{(canEdit || canCreate || canDelete) && <div className="layer-actions"><button className="icon-button" aria-label={`Actions pour ${layer.name}`} aria-expanded={actionMenu} onClick={() => setActionMenu((open) => !open)}><MoreVertical size={19} /></button>{actionMenu && <div className="layer-actions-menu">{canEdit && <button onClick={openEdit}>Modifier</button>}{canCreate && <button onClick={openDuplicate}>Dupliquer</button>}{canEdit && <button onClick={toggleArchive}>{layer.archived ? "Réactiver" : "Archiver"}</button>}<button onClick={() => exportLayerGeoJson(layer, sections)}>Exporter en GeoJSON</button>{canDelete && <button className="danger" onClick={openDelete}>Supprimer</button>}</div>}</div>}</>}
    </div>
    {!layer ? <div className="empty-state"><Map /><strong>Aucune couche métier</strong><span>{showArchived ? "Aucune couche ne correspond à cette vue." : "Créez une couche ou affichez les archives."}</span></div> : <>
      {layer.archived && <div className="archived-layer-notice"><Archive size={18} /><span><strong>Couche archivée.</strong> Ses portions et son historique sont conservés. Réactivez-la pour reprendre les modifications.</span></div>}
      <div className="business-summary"><article><span>Portions</span><strong>{totals.count}</strong></article><article><span>Longueur des voies</span><strong>{formatMeters(totals.roads)}</strong></article><article><span>Linéaire total</span><strong>{formatMeters(totals.all)}</strong></article><article><span>Réalisé</span><strong>{formatMeters(totals.done)}</strong></article><article><span>Restant</span><strong>{formatMeters(totals.todo)}</strong></article></div>
      <section className="business-map-card"><header><div><h3>{layer.name}</h3><p>{layer.description || BUSINESS_KIND_LABELS[layer.kind]} · {layer.year || "Sans campagne"}</p></div>{canEdit && !layer.archived && <button className="primary-button" onClick={() => { resetDrawing(); setDrawingMode("choice"); }}><Route size={16} /> Tracer une portion</button>}</header>
        {drawingMode === "choice" && <div className="drawing-mode-choice"><strong>Comment souhaitez-vous créer la portion ?</strong><button className="primary-button" onClick={() => setDrawingMode("free")}>✏️ Tracé libre</button><button className="secondary-button" onClick={() => setDrawingMode("automatic")}>🛣️ Tracé automatique · Suivre une route ou un chemin</button><button className="secondary-button" onClick={closeDrawing}>Annuler</button></div>}
        {drawingMode === "free" && <div className="map-drawing-toolbar"><div><strong>Tracé libre · {drawing.length} point{drawing.length > 1 ? "s" : ""}</strong><span>Cliquez successivement sur la carte. Longueur : {formatMeters(calculateLineLength(drawing.map(([lat, lon]) => [lon, lat])))}</span></div><button className="secondary-button" disabled={!drawing.length} onClick={() => setDrawing((points) => points.slice(0, -1))}>Annuler le dernier point</button><button className="secondary-button" disabled={!drawing.length} onClick={() => setDrawing([])}>Recommencer</button><button className="secondary-button" onClick={closeDrawing}>Annuler</button></div>}
        {drawingMode === "automatic" && <div className="automatic-routing-panel"><div className="routing-steps"><strong className={routePoints.length === 0 ? "active" : "done"}>1 Départ</strong><strong className={routePoints.length === 1 ? "active" : routePoints.length > 1 ? "done" : ""}>2 Arrivée</strong><strong>+ Point de passage</strong></div><p>{routePoints.length < 2 ? `Cliquez sur la carte pour placer ${routePoints.length === 0 ? "le départ" : "l’arrivée"}.` : "Cliquez encore pour ajouter des points de passage, ou calculez l’itinéraire."}</p><div className="routing-actions"><button className="secondary-button" disabled={!routePoints.length} onClick={() => { setRoutePoints((points) => points.slice(0, -1)); setDrawing([]); setRouteDistance(null); }}>Modifier les points</button><button className="secondary-button" disabled={!routePoints.length} onClick={resetDrawing}>Recommencer</button><button className="primary-button" disabled={routePoints.length < 2 || routing} onClick={calculateRoute}>{routing ? "Calcul…" : drawing.length ? "Recalculer" : "Calculer"}</button><button className="secondary-button" onClick={closeDrawing}>Annuler</button></div>{routeDistance !== null && <strong className="routing-distance">Itinéraire : {routeDistance < 1000 ? `${Math.round(routeDistance)} m` : `${(routeDistance / 1000).toLocaleString("fr-FR", { maximumFractionDigits: 2 })} km`}</strong>}{routingConfiguration.isDevelopmentFallback && <small className="routing-notice">OSRM public est utilisé en développement. Un endpoint maîtrisé est requis en production.</small>}{routingError && <div className="routing-error"><span>{routingError}</span><button className="primary-button" onClick={() => { resetDrawing(); setDrawingMode("free"); }}>Passer au tracé libre</button></div>}</div>}
        <CommuneMap markers={[]} height={460} customLayers={[layer]} customSections={sections} drawingCoordinates={drawing} waypointCoordinates={drawingMode === "automatic" ? routePoints : []} drawingColor={layer.color} onDrawingPoint={drawingMode === "free" ? (lat, lon) => setDrawing((points) => [...points, [lat, lon]]) : drawingMode === "automatic" ? (lat, lon) => { setRoutePoints((points) => [...points, [lat, lon]]); setDrawing([]); setRouteDistance(null); setRoutingError(""); } : undefined} onToggleCustomLayer={store.toggleLayer} />
        {(drawingMode === "free" || drawingMode === "automatic") && drawing.length >= 2 && <form className="portion-inline-form" onSubmit={saveSection}><label>Voie<input required value={sectionForm.name} onChange={(event) => setSectionForm({ ...sectionForm, name: event.target.value })} /></label><label>Secteur<input value={sectionForm.sector} onChange={(event) => setSectionForm({ ...sectionForm, sector: event.target.value })} /></label><label>Côté(s)<select value={sectionForm.side} onChange={(event) => setSectionForm({ ...sectionForm, side: event.target.value as InterventionSide })}><option value="gauche">Gauche</option><option value="droite">Droite</option><option value="deux-cotes">Deux côtés (×2)</option></select></label><button className="primary-button">Enregistrer</button></form>}</section>
      <div className="business-table-wrap print-business-layer" data-layer-id={layer.id}><div className="print-heading"><strong>CommunePilot · Mairie de Montrottier</strong><h2>{layer.name}</h2><span>Édité le {new Date().toLocaleDateString("fr-FR")}</span></div><table className="business-table"><thead><tr><th>Voie</th><th>Secteur</th><th>Longueur</th><th>Côté(s)</th><th>Linéaire métier</th><th>Statut</th><th>Date</th><th className="no-print">Actions</th></tr></thead><tbody>{sections.map((section) => <tr key={section.id}><td><strong>{section.name}</strong>{section.missionId && <small>Mission liée</small>}</td><td>{section.sector || "—"}</td><td>{formatMeters(section.lengthMeters)}</td><td>{section.interventionSide === "deux-cotes" ? "Deux côtés" : section.interventionSide}</td><td>{formatMeters(section.businessLengthMeters)}</td><td><select className={`status-select status-${section.status}`} value={section.status} disabled={layer.archived || (!canEdit && !(user.role === "Agent technique" && Boolean(section.missionId)))} onChange={(event) => changeStatus(section.id, event.target.value as CustomMapLayerStatus)}>{Object.entries(STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></td><td>{section.completionDate || "—"}</td><td className="table-actions no-print">{!layer.archived && can("missions", "create") && !section.missionId && <button onClick={() => createMission(section.id)}>Créer mission</button>}{!layer.archived && canEdit && <button onClick={() => { if (window.confirm("Supprimer cette portion ?")) store.removeSection(section.id); }}>Supprimer</button>}</td></tr>)}</tbody><tfoot><tr><th colSpan={2}>Totaux</th><th>{formatMeters(totals.roads)}</th><th></th><th>{formatMeters(totals.all)}</th><th colSpan={3}>Réalisé {formatMeters(totals.done)} · Restant {formatMeters(totals.todo)}</th></tr></tfoot></table></div>
    </>}
    {(modal === "create" || modal === "edit" || modal === "duplicate") && <LayerFormModal mode={modal} form={layerForm} setForm={setLayerForm} copySections={copySections} setCopySections={setCopySections} sectionCount={sections.length} onClose={() => setModal(null)} onSubmit={submitLayer} />}
    {modal === "delete" && layer && <div className="modal-backdrop"><div className="modal danger-modal"><div className="modal-header"><div><span className="eyebrow">Suppression définitive</span><h3>Supprimer « {layer.name} »</h3></div><button className="icon-button" onClick={() => setModal(null)}>×</button></div><div className="delete-impact"><strong>Impact détecté</strong><ul><li>{impact.portions} portion(s) supprimée(s)</li><li>{impact.missions} mission(s) conservée(s)</li><li>{impact.dossiers} dossier(s) conservé(s)</li><li>{impact.history} entrée(s) d’historique</li></ul></div><div className="blocking-notice"><strong>Cette action est irréversible.</strong><span>Pour conserver le calque et ses portions, utilisez plutôt « Archiver ».</span></div><label>Pour confirmer, saisissez exactement <strong>{layer.name}</strong><input value={deleteConfirmation} onChange={(event) => setDeleteConfirmation(event.target.value)} /></label><div className="modal-actions"><button className="secondary-button" onClick={() => exportLayerCsv(layer, sections)}><Download size={16} /> Exporter CSV</button><button className="secondary-button" onClick={() => exportLayerGeoJson(layer, sections)}><FileJson size={16} /> Exporter GeoJSON</button><button className="secondary-button" onClick={() => setModal(null)}>Annuler</button><button className="danger-button" disabled={deleteConfirmation !== layer.name} onClick={confirmDelete}>Supprimer le calque et ses portions</button></div></div></div>}
    {importSummary && <div className="modal-backdrop"><div className="modal import-modal"><div className="modal-header"><div><h3>Aperçu de l’import</h3><p>{importSummary.total} objets analysés · {importCandidates.length} lignes candidates · {importSummary.ignored} ignorés</p></div><button className="icon-button" onClick={() => setImportSummary(null)}>×</button></div><div className="import-candidates">{importCandidates.map((candidate, index) => <label key={index}><input type="checkbox" checked={candidate.selected} onChange={(event) => setImportCandidates((list) => list.map((item, itemIndex) => itemIndex === index ? { ...item, selected: event.target.checked } : item))} /><span><strong>{candidate.name}</strong><small>LineString · {candidate.geometry.coordinates.length} points</small></span></label>)}</div><div className="modal-actions"><span>{importCandidates.filter((candidate) => candidate.selected).length} sélectionnée(s)</span><button className="primary-button" disabled={!importCandidates.some((candidate) => candidate.selected)} onClick={importSelected}>Importer la sélection</button></div></div></div>}
  </section>;
}

function LayerFormModal({ mode, form, setForm, copySections, setCopySections, sectionCount, onClose, onSubmit }: { mode: "create" | "edit" | "duplicate"; form: ReturnType<typeof blankLayerForm>; setForm: React.Dispatch<React.SetStateAction<ReturnType<typeof blankLayerForm>>>; copySections: boolean; setCopySections: (value: boolean) => void; sectionCount: number; onClose: () => void; onSubmit: (event: React.FormEvent) => void }) {
  const title = mode === "create" ? "Nouvelle couche métier" : mode === "edit" ? "Modifier la couche" : "Dupliquer la couche";
  return <div className="modal-backdrop"><div className="modal"><div className="modal-header"><h3>{title}</h3><button className="icon-button" onClick={onClose}>×</button></div><form className="field-form" onSubmit={onSubmit}><label>Nom<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><div className="form-row"><label>Type métier<select value={form.kind} onChange={(event) => setForm({ ...form, kind: event.target.value as CustomMapLayerKind })}>{BUSINESS_LAYER_KINDS.map((kind) => <option value={kind} key={kind}>{BUSINESS_KIND_LABELS[kind]}</option>)}</select></label><label>Année / campagne<input type="number" value={form.year} onChange={(event) => setForm({ ...form, year: Number(event.target.value) })} /></label></div><label>Description<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label>Couleur<input className="custom-layer-color" type="color" value={form.color} onChange={(event) => setForm({ ...form, color: event.target.value })} /></label>{mode === "edit" && <label className="toggle-row"><input type="checkbox" checked={!form.archived} onChange={(event) => setForm({ ...form, active: event.target.checked, archived: !event.target.checked })} /> Couche active</label>}{mode === "duplicate" && <label className="copy-sections-option"><input type="checkbox" checked={copySections} onChange={(event) => setCopySections(event.target.checked)} /><span><strong>Copier aussi les {sectionCount} portion(s)</strong><small>Désactivé par défaut. Les copies seront indépendantes et sans lien mission/dossier.</small></span></label>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Annuler</button><button className="primary-button">{mode === "edit" ? "Enregistrer" : mode === "duplicate" ? "Dupliquer" : "Créer"}</button></div></form></div></div>;
}
