import { useEffect, useState } from "react";
import type { CommuneUser } from "../../access/types";
import type { Dossier } from "../../dossiers/types/dossier";
import type { Mission } from "../../field/types";
import { EVENT_TYPES, type CalendarEvent, type CalendarEventStatus, type EventVisibility } from "../types";

export type EventFormValue = Omit<CalendarEvent, "id" | "createdAt" | "updatedAt" | "createdBy">;
const nowLocal = () => { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); };

export default function EventForm({ event, users, dossiers, missions, organizerId, initialCategory = "", onClose, onSubmit, onCreateDossier }: { event?: CalendarEvent; users: CommuneUser[]; dossiers: Dossier[]; missions: Mission[]; organizerId: string; initialCategory?: string; onClose(): void; onSubmit(value: EventFormValue): void; onCreateDossier?(): void }) {
  const [form, setForm] = useState<EventFormValue>(() => ({...emptyValue(organizerId),category:initialCategory}));
  useEffect(() => setForm(event ? { title:event.title,type:event.type,description:event.description,startAt:event.startAt.slice(0,16),endAt:event.endAt.slice(0,16),allDay:event.allDay,location:event.location,address:event.address,participantIds:event.participantIds,organizerId:event.organizerId,status:event.status,color:event.color,category:event.category,dossierId:event.dossierId,missionId:event.missionId,attachments:event.attachments,notes:event.notes,visibility:event.visibility,reminders:event.reminders } : {...emptyValue(organizerId),category:initialCategory}), [event, organizerId, initialCategory]);
  const update = <K extends keyof EventFormValue>(key: K, value: EventFormValue[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (new Date(form.endAt) < new Date(form.startAt)) { window.alert("La fin doit être postérieure au début."); return; } onSubmit({ ...form, title: form.title.trim(), description: form.description.trim(), category: form.category.trim(), location: form.location.trim(), address: form.address.trim(), notes: form.notes.trim() }); };
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal calendar-event-modal" onMouseDown={(e)=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label={event?"Modifier l’événement":"Créer un événement"}><div className="modal-header"><div><span className="eyebrow">Calendrier municipal</span><h3>{event?"Modifier l’événement":"Nouvel événement"}</h3></div><button className="icon-button" onClick={onClose} aria-label="Fermer">×</button></div><form className="calendar-event-form" onSubmit={submit}>
    <label className="form-wide">Titre<input autoFocus required value={form.title} onChange={(e)=>update("title",e.target.value)}/></label>
    <label>Type<select value={form.type} onChange={(e)=>update("type",e.target.value as EventFormValue["type"])}>{EVENT_TYPES.map((type)=><option key={type}>{type}</option>)}</select></label>
    <label>Catégorie / commission<input value={form.category} onChange={(e)=>update("category",e.target.value)} placeholder="Ex. Finances"/></label>
    <label className="form-wide">Description<textarea rows={3} value={form.description} onChange={(e)=>update("description",e.target.value)}/></label>
    <label className="toggle-row form-wide"><input type="checkbox" checked={form.allDay} onChange={(e)=>update("allDay",e.target.checked)}/> Journée entière</label>
    <label>Début<input required type={form.allDay?"date":"datetime-local"} value={form.startAt.slice(0,form.allDay?10:16)} onChange={(e)=>update("startAt",form.allDay?`${e.target.value}T00:00`:e.target.value)}/></label>
    <label>Fin<input required type={form.allDay?"date":"datetime-local"} value={form.endAt.slice(0,form.allDay?10:16)} onChange={(e)=>update("endAt",form.allDay?`${e.target.value}T23:59`:e.target.value)}/></label>
    <label>Lieu<input value={form.location} onChange={(e)=>update("location",e.target.value)}/></label><label>Adresse<input value={form.address} onChange={(e)=>update("address",e.target.value)}/></label>
    <label>Responsable<select value={form.organizerId} onChange={(e)=>update("organizerId",e.target.value)}>{users.filter((u)=>u.active).map((u)=><option value={u.id} key={u.id}>{u.firstName} {u.lastName}</option>)}</select></label>
    <label>Statut<select value={form.status} onChange={(e)=>update("status",e.target.value as CalendarEventStatus)}><option>Planifié</option><option>Confirmé</option><option>Annulé</option><option>Terminé</option></select></label>
    <fieldset className="form-wide"><legend>Participants</legend><div className="calendar-participants">{users.filter((u)=>u.active).map((u)=><label className="toggle-row" key={u.id}><input type="checkbox" checked={form.participantIds.includes(u.id)} onChange={(e)=>update("participantIds",e.target.checked?[...form.participantIds,u.id]:form.participantIds.filter((id)=>id!==u.id))}/>{u.firstName} {u.lastName} · {u.role}</label>)}</div></fieldset>
    <label>Visibilité<select value={form.visibility} onChange={(e)=>update("visibility",e.target.value as EventVisibility)}><option>Public mairie</option><option>Restreint participants</option><option>Privé responsable</option></select></label>
    <label>Couleur<input type="color" value={form.color} onChange={(e)=>update("color",e.target.value)}/></label>
    <label>Dossier lié<span className="calendar-linked-control"><select value={form.dossierId??""} onChange={(e)=>update("dossierId",e.target.value?Number(e.target.value):undefined)}><option value="">Aucun</option>{dossiers.map((d)=><option value={d.id} key={d.id}>{d.title}</option>)}</select>{onCreateDossier&&<button type="button" className="secondary-button" onClick={onCreateDossier}>Créer</button>}</span></label>
    <label>Mission liée<select value={form.missionId??""} onChange={(e)=>update("missionId",e.target.value||undefined)}><option value="">Aucune</option>{missions.map((m)=><option value={m.id} key={m.id}>{m.title}</option>)}</select></label>
    <fieldset className="form-wide"><legend>Rappels locaux</legend><div className="calendar-reminders">{[[0,"Au moment"],[15,"15 min"],[60,"1 h"],[1440,"1 jour"],[10080,"1 semaine"]].map(([minutes,label])=><label className="toggle-row" key={minutes}><input type="checkbox" checked={form.reminders.some((r)=>r.minutesBefore===minutes)} onChange={(e)=>update("reminders",e.target.checked?[...form.reminders,{id:`rem-${minutes}-${Date.now()}`,minutesBefore:Number(minutes)}]:form.reminders.filter((r)=>r.minutesBefore!==minutes))}/>{label}</label>)}</div><label>Personnalisé (minutes)<input type="number" min="1" onBlur={(e)=>{const value=Number(e.target.value);if(value&&!form.reminders.some((r)=>r.minutesBefore===value))update("reminders",[...form.reminders,{id:`rem-custom-${Date.now()}`,minutesBefore:value}]);}}/></label></fieldset>
    <label className="form-wide">Documents / liens (un lien par ligne)<textarea rows={2} value={form.attachments.map((a)=>`${a.label}|${a.url}`).join("\n")} onChange={(e)=>update("attachments",e.target.value.split("\n").filter(Boolean).map((line,index)=>{const [label,url]=line.split("|");return{id:`link-${index}`,label:label||url,url:url||label};}))}/></label>
    <label className="form-wide">Notes<textarea rows={2} value={form.notes} onChange={(e)=>update("notes",e.target.value)}/></label>
    <div className="modal-actions form-wide"><button type="button" className="secondary-button" onClick={onClose}>Annuler</button><button className="primary-button">Enregistrer</button></div>
  </form></div></div>;
}
function emptyValue(organizerId: string): EventFormValue { const start=nowLocal(); const end=new Date(new Date(start).getTime()+3_600_000); end.setMinutes(end.getMinutes()-end.getTimezoneOffset()); return { title:"",type:"Réunion",description:"",startAt:start,endAt:end.toISOString().slice(0,16),allDay:false,location:"",address:"",participantIds:[],organizerId,status:"Planifié",color:"#5b7fd6",category:"",attachments:[],notes:"",visibility:"Public mairie",reminders:[] }; }
