import { useEffect, useMemo, useState } from "react";
import { Archive, Mail, Pencil, Phone, Plus, Search, UserRound, X } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import { COMMISSIONS } from "../commissions/commissions";
import { useIdentity } from "./LocalIdentityProvider";
import { roles, userGroups, type CommuneUser, type UserGroup, type UserRole } from "./types";
import { uploadDirectoryPhoto, useDirectory } from "./useDirectory";

const emptyUser = (): CommuneUser => { const now = new Date().toISOString(); return { id: `user-${crypto.randomUUID()}`, firstName: "", lastName: "", role: "Conseiller", group: "Conseillers municipaux", jobTitle: "", active: true, addressVisibility: "administrators", commissionIds: [], createdAt: now, updatedAt: now }; };

export default function UsersPage() {
  const [params, setParams] = useSearchParams();
  const { can } = useIdentity(); const { users, loading, error, save } = useDirectory();
  const [query, setQuery] = useState(""); const [group, setGroup] = useState(""); const [commission, setCommission] = useState(""); const [editing, setEditing] = useState<CommuneUser | null>(null);
  useEffect(() => { if (params.get("new") === "1" && can("utilisateurs", "create")) setEditing(emptyUser()); }, [params, can]);
  const closeForm = () => { setEditing(null); if (params.has("new")) { const next = new URLSearchParams(params); next.delete("new"); setParams(next, { replace: true }); } };
  const filtered = useMemo(() => users.filter((user) => { const haystack = `${user.firstName} ${user.lastName} ${user.jobTitle} ${user.email ?? ""}`.toLocaleLowerCase("fr"); return (!query || haystack.includes(query.toLocaleLowerCase("fr"))) && (!group || user.group === group) && (!commission || user.commissionIds.includes(commission)); }).sort((a, b) => Number(b.active) - Number(a.active) || a.lastName.localeCompare(b.lastName, "fr")), [users, query, group, commission]);
  return <section className="directory-page"><div className="page-heading"><div><span className="eyebrow">Annuaire partagé</span><h2>Utilisateurs</h2><p>Une fiche unique, réutilisable dans les contacts, missions, commissions et services.</p></div>{can("utilisateurs", "create") && <button className="primary-button" onClick={() => setEditing(emptyUser())}><Plus/>Ajouter un membre</button>}</div>
    {error && <div className="local-mode-notice">Mode hors ligne : le cache local est affiché. {error}</div>}
    <div className="directory-toolbar"><label><Search/><input aria-label="Rechercher" placeholder="Rechercher un nom, une fonction…" value={query} onChange={(event) => setQuery(event.target.value)}/></label><select aria-label="Filtrer par groupe" value={group} onChange={(event) => setGroup(event.target.value)}><option value="">Tous les groupes</option>{userGroups.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Filtrer par commission" value={commission} onChange={(event) => setCommission(event.target.value)}><option value="">Toutes les commissions</option>{COMMISSIONS.map((value) => <option value={value.id} key={value.id}>{value.label}</option>)}</select></div>
    {loading && <p className="directory-status">Chargement de l’annuaire…</p>}
    <div className="directory-grid">{filtered.map((contact) => <article className={`directory-card${contact.active ? "" : " is-inactive"}`} key={contact.id}><div className="directory-avatar">{contact.thumbnailUrl ? <img src={contact.thumbnailUrl} alt=""/> : <UserRound/>}</div><div className="directory-card-copy"><div><strong>{contact.firstName} {contact.lastName}</strong>{!contact.active && <span>Inactif</span>}</div><p>{contact.jobTitle || contact.group}</p><small>{contact.group}</small><div className="directory-commissions">{contact.commissionIds.map((id) => <span key={id}>{COMMISSIONS.find((item) => item.id === id)?.label ?? id}</span>)}</div></div><div className="directory-actions">{contact.phone && <a href={`tel:${contact.phone.replace(/\s/g, "")}`}><Phone/> {contact.phone}</a>}{contact.email && <a href={`mailto:${contact.email}`}><Mail/> {contact.email}</a>}{can("utilisateurs", "update") && <button className="secondary-button" onClick={() => setEditing(contact)}><Pencil/>Modifier</button>}</div></article>)}{!loading && !filtered.length && <div className="empty-state"><UserRound/><strong>Aucun contact</strong><span>Ajoutez un membre ou modifiez les filtres.</span></div>}</div>
    {editing && <UserForm initial={editing} onClose={closeForm} onSave={async (value) => { await save(value); closeForm(); }}/>} </section>;
}

function UserForm({ initial, onClose, onSave }: { initial: CommuneUser; onClose(): void; onSave(value: CommuneUser): Promise<void> }) {
  const [form, setForm] = useState(initial); const [photo, setPhoto] = useState<File>(); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const update = <K extends keyof CommuneUser>(key: K, value: CommuneUser[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { let value = form; if (photo) value = { ...value, ...(await uploadDirectoryPhoto(photo, form.id)) }; await onSave(value); } catch (reason) { setError(reason instanceof Error ? reason.message : "Enregistrement impossible."); } finally { setSaving(false); } };
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal directory-modal" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><div className="modal-header"><div><span className="eyebrow">Fiche annuaire</span><h3>{initial.firstName ? "Modifier le membre" : "Nouveau membre"}</h3></div><button className="icon-button" onClick={onClose} aria-label="Fermer"><X/></button></div><form className="directory-form" onSubmit={submit}>
    <label>Prénom<input required value={form.firstName} onChange={(e) => update("firstName", e.target.value)}/></label><label>Nom<input required value={form.lastName} onChange={(e) => update("lastName", e.target.value)}/></label>
    <label>Fonction / intitulé<input required value={form.jobTitle} onChange={(e) => update("jobTitle", e.target.value)}/></label><label>Groupe métier<select value={form.group} onChange={(e) => update("group", e.target.value as UserGroup)}>{userGroups.map((value) => <option key={value}>{value}</option>)}</select></label>
    <label>Rôle d’accès<select value={form.role} onChange={(e) => update("role", e.target.value as UserRole)}>{roles.map((value) => <option key={value}>{value}</option>)}</select><small>Détermine les permissions, indépendamment du groupe métier.</small></label><label>Photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => setPhoto(e.target.files?.[0])}/></label>
    <label>E-mail professionnel<input type="email" value={form.email ?? ""} onChange={(e) => update("email", e.target.value)}/></label><label>Téléphone<input type="tel" value={form.phone ?? ""} onChange={(e) => update("phone", e.target.value)}/></label>
    <label className="form-wide">Adresse<textarea rows={2} value={form.address ?? ""} onChange={(e) => update("address", e.target.value)}/></label><label>Visibilité de l’adresse<select value={form.addressVisibility} onChange={(e) => update("addressVisibility", e.target.value as CommuneUser["addressVisibility"])}><option value="administrators">Administration uniquement</option><option value="directory">Annuaire autorisé</option></select></label>
    <fieldset className="form-wide"><legend>Commissions</legend><div className="directory-checks">{COMMISSIONS.map((item) => <label key={item.id}><input type="checkbox" checked={form.commissionIds.includes(item.id)} onChange={(e) => update("commissionIds", e.target.checked ? [...form.commissionIds, item.id] : form.commissionIds.filter((id) => id !== item.id))}/>{item.label}</label>)}</div></fieldset>
    <label className="form-wide">Notes professionnelles<textarea rows={3} value={form.notes ?? ""} onChange={(e) => update("notes", e.target.value)}/></label><label className="toggle-row form-wide"><input type="checkbox" checked={form.active} onChange={(e) => update("active", e.target.checked)}/>{form.active ? "Profil actif" : "Profil archivé"}</label>
    {error && <p className="field-error form-wide" role="alert">{error}</p>}<div className="modal-actions form-wide">{initial.firstName && initial.active && <button type="button" className="secondary-button" onClick={() => update("active", false)}><Archive/>Désactiver</button>}<button type="button" className="secondary-button" onClick={onClose}>Annuler</button><button className="primary-button" disabled={saving}>{saving ? "Enregistrement…" : "Enregistrer"}</button></div>
  </form></div></div>;
}
