import {
  Building2,
  CalendarDays,
  FileText,
  FolderKanban,
  Gauge,
  Landmark,
  Mail,
  Map,
  MapPin,
  Settings,
  Users,
  Warehouse,
  Megaphone,
} from "lucide-react";

export const navigationItems = [
  { label: "Tableau de bord", path: "/dashboard", icon: Gauge, domain: "dashboard" },
  { label: "Dossiers", path: "/dossiers", icon: FolderKanban, domain: "dossiers" },
  { label: "Voirie", path: "/voirie", icon: MapPin, domain: "equipements" },
  { label: "Conseil municipal", path: "/conseil-municipal", icon: Landmark },
  { label: "Bâtiments", path: "/batiments", icon: Building2 },
  { label: "Gestion des salles", path: "/gestion-des-salles", icon: Warehouse, domain: "dashboard" },
  { label: "Communication", path: "/communication", icon: Megaphone, domain: "dashboard" },
  { label: "Mails", path: "/mails", icon: Mail, domain: "mails" },
  { label: "Documents", path: "/documents", icon: FileText, domain: "documents" },
  { label: "Calendrier", path: "/calendrier", icon: CalendarDays, domain: "calendrier" },
  { label: "Carte", path: "/carte", icon: Map, domain: "carte" },
  { label: "Paramètres", path: "/parametres", icon: Settings },
  { label: "Utilisateurs", path: "/utilisateurs", icon: Users, domain: "utilisateurs" },
] as const;
