import {
  Building2,
  CalendarDays,
  FileText,
  FolderKanban,
  Gauge,
  Landmark,
  Mail,
  Map,
  MapPin,
  Settings,
  ClipboardList,
  Users,
  Siren,
  TriangleAlert,
} from "lucide-react";

export const navigationItems = [
  { label: "Tableau de bord", path: "/dashboard", icon: Gauge, domain: "dashboard" },
  { label: "Dossiers", path: "/dossiers", icon: FolderKanban, domain: "dossiers" },
  { label: "Voirie", path: "/voirie", icon: MapPin, domain: "equipements" },
  { label: "Missions", path: "/missions", icon: ClipboardList, domain: "missions" },
  { label: "Alertes terrain", path: "/alertes-terrain", icon: Siren, domain: "signalements" },
  { label: "Signalements", path: "/signalements", icon: TriangleAlert, domain: "signalements" },
  { label: "Conseil municipal", path: "/conseil-municipal", icon: Landmark },
  { label: "Bâtiments", path: "/batiments", icon: Building2 },
  { label: "Mails", path: "/mails", icon: Mail, domain: "mails" },
  { label: "Documents", path: "/documents", icon: FileText, domain: "documents" },
  { label: "Calendrier", path: "/calendrier", icon: CalendarDays, domain: "calendrier" },
  { label: "Carte", path: "/carte", icon: Map, domain: "carte" },
  { label: "Paramètres", path: "/parametres", icon: Settings },
  { label: "Utilisateurs", path: "/utilisateurs", icon: Users, domain: "utilisateurs" },
] as const;
