import type { MailPage, MailProvider } from "./mailProvider";
import type { MailAttachment, MunicipalMail } from "../types/mail";
const GRAPH_ROOT = "https://graph.microsoft.com/v1.0";
// Le corps HTML complet peut dépasser rapidement le quota local de Safari.
// L'aperçu Graph est borné et suffit à la synchronisation locale initiale.
const messageFields = "id,subject,from,toRecipients,ccRecipients,receivedDateTime,bodyPreview,isRead,hasAttachments,webLink";
interface GraphAddress { emailAddress?: { name?: string; address?: string } }
interface GraphMessage { id: string; subject?: string; from?: GraphAddress; toRecipients?: GraphAddress[]; ccRecipients?: GraphAddress[]; receivedDateTime?: string; bodyPreview?: string; isRead?: boolean; hasAttachments?: boolean; webLink?: string; }
interface GraphAttachment { id: string; name?: string; size?: number; contentType?: string; isInline?: boolean }
interface GraphPage<T> { value?: T[]; "@odata.nextLink"?: string; "@odata.deltaLink"?: string }
function numericId(externalId: string) { let hash = 0; for (const character of externalId) hash = Math.imul(31, hash) + character.charCodeAt(0) | 0; return 2_000_000_000 + Math.abs(hash % 100_000_000); }
export class MicrosoftGraphMailProvider implements MailProvider {
  private readonly getToken: () => Promise<string>;
  constructor(getToken: () => Promise<string>) { this.getToken = getToken; }
  private async request<T>(url: string): Promise<T> { const token = await this.getToken(); const response = await fetch(url, { headers: { Authorization: `Bearer ${token}`, Accept: "application/json" } }); if (!response.ok) { const detail = await response.json().catch(() => null) as { error?: { message?: string } } | null; throw new Error(detail?.error?.message || `Microsoft Graph a répondu ${response.status}.`); } return response.json() as Promise<T>; }
  private async attachments(message: GraphMessage): Promise<MailAttachment[]> { if (!message.hasAttachments) return []; const page = await this.request<GraphPage<GraphAttachment>>(`${GRAPH_ROOT}/me/messages/${encodeURIComponent(message.id)}/attachments?$select=id,name,size,contentType,isInline`); return (page.value ?? []).filter((item) => item.id && item.name).map((item) => ({ id: item.id, name: item.name!, size: item.size, mimeType: item.contentType, isInline: item.isInline })); }
  async getMessages(cursor?: string): Promise<MailPage> { const url = cursor || `${GRAPH_ROOT}/me/mailFolders/inbox/messages?$top=25&$orderby=receivedDateTime%20desc&$select=${messageFields}`; if (!url.startsWith(`${GRAPH_ROOT}/`)) throw new Error("Curseur Microsoft Graph invalide."); const page = await this.request<GraphPage<GraphMessage>>(url); const mails = await Promise.all((page.value ?? []).map(async (message): Promise<MunicipalMail> => { const sender = message.from?.emailAddress; const receivedAt = message.receivedDateTime || new Date().toISOString(); return { id: numericId(message.id), externalId: message.id, sender: sender?.name || sender?.address || "Expéditeur inconnu", senderEmail: sender?.address, recipients: [...(message.toRecipients ?? []), ...(message.ccRecipients ?? [])].map((item) => item.emailAddress?.address).filter((address): address is string => Boolean(address)), subject: message.subject || "(Sans objet)", preview: message.bodyPreview || "", content: message.bodyPreview || "", receivedAt, status: "À traiter", attachments: await this.attachments(message), followUps: [], source: "outlook", isRead: message.isRead, hasAttachments: message.hasAttachments, webUrl: message.webLink, internalNotes: "", updatedAt: new Date().toISOString() }; })); return { mails, nextCursor: page["@odata.nextLink"], deltaCursor: page["@odata.deltaLink"] }; }
  async getAttachment(messageId: string, attachmentId: string): Promise<Blob> { const token = await this.getToken(); const response = await fetch(`${GRAPH_ROOT}/me/messages/${encodeURIComponent(messageId)}/attachments/${encodeURIComponent(attachmentId)}/$value`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(`Téléchargement impossible (${response.status}).`); return response.blob(); }
}
