import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Download, FileDown, ListFilter, Plus, Printer, Search, Trash2 } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { useIdentity } from "../../access/LocalIdentityProvider";
import DossierForm from "../../dossiers/components/DossierForm";
import { initialDossiers } from "../../dossiers/data/dossiers";
import { dossierActivityRepository } from "../../dossiers/services/dossierActivityRepository";
import { loadDossiers, saveDossiers } from "../../dossiers/services/dossierStorage";
import type { Dossier } from "../../dossiers/types/dossier";
import { useFieldData } from "../../field/useFieldData";
import { useRoadEquipment } from "../../road-equipment/hooks/useRoadEquipment";
import EventForm, { type EventFormValue } from "../components/EventForm";
import { exportCsv, exportIcs } from "../services/calendarExport";
import { buildCalendarItems, canSeeCalendarItem } from "../services/calendarIntegration";
import { processCalendarReminders } from "../services/calendarNotifications";
import { calendarAuditRepository, calendarRepository } from "../services/calendarRepository";
import { EVENT_TYPES, type CalendarEvent, type CalendarItem } from "../types";

type CalendarView = "month" | "week" | "day" | "list";
const labels: Record<CalendarView,string>={month:"Mois",week:"Semaine",day:"Jour",list:"Liste"};
const sourceLabels={manual:"Événement",mission:"Mission",dossier:"Dossier",equipment:"Équipement",google:"Google", "microsoft-graph":"Outlook"};
const pad=(n:number)=>String(n).padStart(2,"0");
const dayKey=(date:Date)=>`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;
const itemDay=(item:CalendarItem)=>item.startAt.slice(0,10);
function periodStart(anchor:Date,view:CalendarView){const date=new Date(anchor);date.setHours(0,0,0,0);if(view==="month")date.setDate(1);if(view==="week"){const day=(date.getDay()+6)%7;date.setDate(date.getDate()-day);}return date;}
function periodEnd(anchor:Date,view:CalendarView){const start=periodStart(anchor,view);const end=new Date(start);if(view==="month")end.setMonth(end.getMonth()+1);else if(view==="week")end.setDate(end.getDate()+7);else if(view==="day")end.setDate(end.getDate()+1);else end.setFullYear(end.getFullYear()+10);return end;}
function periodLabel(anchor:Date,view:CalendarView){if(view==="month")return anchor.toLocaleDateString("fr-FR",{month:"long",year:"numeric"});if(view==="day")return anchor.toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric"});if(view==="list")return "Agenda à venir";const start=periodStart(anchor,"week"),end=new Date(start);end.setDate(end.getDate()+6);return `${start.toLocaleDateString("fr-FR",{day:"numeric",month:"short"})} – ${end.toLocaleDateString("fr-FR",{day:"numeric",month:"short",year:"numeric"})}`;}
function formatTime(item:CalendarItem){return item.allDay?"Journée":new Date(item.startAt).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"});}

export default function CalendarPage(){
 const {user,users,can}=useIdentity();const {missions}=useFieldData();const {equipment}=useRoadEquipment();const [params,setParams]=useSearchParams();
 const [events,setEvents]=useState(calendarRepository.list);const [dossiers,setDossiers]=useState(()=>loadDossiers()??initialDossiers);const [view,setView]=useState<CalendarView>(()=>matchMedia("(max-width: 700px)").matches?"list":"month");const [anchor,setAnchor]=useState(new Date());
 const [editing,setEditing]=useState<CalendarEvent>();const [formOpen,setFormOpen]=useState(false);const [dossierOpen,setDossierOpen]=useState(false);const [selected,setSelected]=useState<CalendarItem>();const [search,setSearch]=useState("");const [type,setType]=useState("");const [responsible,setResponsible]=useState("");const [participant,setParticipant]=useState("");const [dossierFilter,setDossierFilter]=useState("");const [missionFilter,setMissionFilter]=useState("");const [status,setStatus]=useState("");const [category,setCategory]=useState("");
 useEffect(()=>calendarRepository.subscribe(()=>setEvents(calendarRepository.list())),[]);useEffect(()=>{processCalendarReminders();},[]);
 const commissionContext=params.get("commission")??"";
 useEffect(()=>{if(commissionContext)setCategory(commissionContext);},[commissionContext]);
 const allItems=useMemo(()=>buildCalendarItems(events,missions,dossiers,equipment).filter((item)=>canSeeCalendarItem(item,user)),[events,missions,dossiers,equipment,user]);
 const filtered=useMemo(()=>allItems.filter((item)=>{const query=search.trim().toLocaleLowerCase("fr");return(!query||[item.title,item.description,item.location,item.address,item.category].some((v)=>v.toLocaleLowerCase("fr").includes(query)))&&(!type||item.type===type)&&(!responsible||item.organizerId===responsible)&&(!participant||item.participantIds.includes(participant))&&(!dossierFilter||String(item.dossierId)===dossierFilter)&&(!missionFilter||item.missionId===missionFilter)&&(!status||item.status===status)&&(!category||item.category===category)}),[allItems,search,type,responsible,participant,dossierFilter,missionFilter,status,category]);
 const visible=useMemo(()=>{if(view==="list")return filtered.filter((i)=>new Date(i.endAt)>=new Date(new Date().setHours(0,0,0,0))).slice(0,100);const start=periodStart(anchor,view),end=periodEnd(anchor,view);return filtered.filter((i)=>new Date(i.startAt)<end&&new Date(i.endAt)>=start)},[filtered,anchor,view]);
 useEffect(()=>{const id=params.get("event");if(!id)return;const found=allItems.find((item)=>item.id===id);if(found)setSelected(found);},[params,allItems]);
 const move=(direction:number)=>setAnchor((current)=>{const next=new Date(current);if(view==="month")next.setMonth(next.getMonth()+direction);else next.setDate(next.getDate()+direction*(view==="week"?7:1));return next;});
 const recordDossier=(event:CalendarEvent,action:string,label:string,previous?:CalendarEvent)=>{const ids=new Set([event.dossierId,previous?.dossierId].filter((id):id is number=>Boolean(id)));ids.forEach((dossierId)=>dossierActivityRepository.add({dossierId,type:"calendar",action,label,authorId:user.id,calendarEventId:event.id}));};
 const save=(value:EventFormValue)=>{const now=new Date().toISOString();const event:CalendarEvent=editing?{...editing,...value,updatedAt:now}:{...value,id:`event-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,createdAt:now,updatedAt:now,createdBy:user.id};calendarRepository.save(event);calendarAuditRepository.add({eventId:event.id,authorId:user.id,action:editing?"updated":"created",label:editing?`Événement modifié : ${event.title}`:`Événement créé : ${event.title}`});recordDossier(event,editing?"updated":"created",editing?`Événement calendrier modifié : ${event.title}`:`Événement calendrier créé : ${event.title}`,editing);setFormOpen(false);setEditing(undefined);setSelected({...event,source:"manual",sourceId:event.id,readOnly:false});};
 const remove=(event:CalendarEvent)=>{if(!can("calendrier","delete")||!confirm(`Supprimer « ${event.title} » ?`))return;calendarRepository.remove(event.id);calendarAuditRepository.add({eventId:event.id,authorId:user.id,action:"deleted",label:`Événement supprimé : ${event.title}`});recordDossier(event,"deleted",`Événement calendrier supprimé : ${event.title}`);setSelected(undefined);};
 const createDossier=(value:Omit<Dossier,"id"|"createdAt"|"updatedAt">)=>{const now=new Date().toISOString();const dossier={...value,id:Date.now(),createdAt:now,updatedAt:now};const next=[dossier,...dossiers];setDossiers(next);saveDossiers(next);setDossierOpen(false);};
 const selectItem=(item:CalendarItem)=>{setSelected(item);setParams({event:item.id},{replace:true});};
 return <section className="calendar-page"><div className="page-heading calendar-heading"><div><span className="eyebrow">Bloc 14 · Agenda partagé</span><h2>Calendrier municipal</h2><p>Événements, missions et échéances réunis sans duplication.</p></div>{can("calendrier","create")&&<button className="primary-button" onClick={()=>{setEditing(undefined);setFormOpen(true)}}><Plus/> Nouvel événement</button>}</div>
 <div className="calendar-toolbar"><div className="calendar-nav"><button aria-label="Période précédente" onClick={()=>move(-1)}><ChevronLeft/></button><button onClick={()=>setAnchor(new Date())}>Aujourd’hui</button><button aria-label="Période suivante" onClick={()=>move(1)}><ChevronRight/></button><strong>{periodLabel(anchor,view)}</strong></div><div className="calendar-view-switch" role="group" aria-label="Vue calendrier">{(Object.keys(labels) as CalendarView[]).map((key)=><button className={view===key?"active":""} onClick={()=>setView(key)} key={key}>{labels[key]}</button>)}</div><div className="calendar-export"><button onClick={()=>window.print()}><Printer/> Imprimer</button><button onClick={()=>exportCsv(visible)}><FileDown/> CSV</button><button onClick={()=>exportIcs(visible)}><Download/> ICS</button></div></div>
 <details className="calendar-filters" open><summary><ListFilter/> Filtres</summary><div className="calendar-filter-grid"><label className="calendar-search"><Search/><input type="search" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Rechercher…"/></label><label>Type<select value={type} onChange={(e)=>setType(e.target.value)}><option value="">Tous</option>{EVENT_TYPES.map((v)=><option key={v}>{v}</option>)}</select></label><label>Catégorie<select value={category} onChange={(e)=>setCategory(e.target.value)}><option value="">Toutes</option>{[...new Set(allItems.map((i)=>i.category).filter(Boolean))].map((v)=><option key={v}>{v}</option>)}</select></label><label>Responsable<select value={responsible} onChange={(e)=>setResponsible(e.target.value)}><option value="">Tous</option>{users.map((u)=><option value={u.id} key={u.id}>{u.firstName} {u.lastName}</option>)}</select></label><label>Participant<select value={participant} onChange={(e)=>setParticipant(e.target.value)}><option value="">Tous</option>{users.map((u)=><option value={u.id} key={u.id}>{u.firstName} {u.lastName}</option>)}</select></label><label>Dossier<select value={dossierFilter} onChange={(e)=>setDossierFilter(e.target.value)}><option value="">Tous</option>{dossiers.map((d)=><option value={d.id} key={d.id}>{d.title}</option>)}</select></label><label>Mission<select value={missionFilter} onChange={(e)=>setMissionFilter(e.target.value)}><option value="">Toutes</option>{missions.map((m)=><option value={m.id} key={m.id}>{m.title}</option>)}</select></label><label>Statut<select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">Tous</option><option>Planifié</option><option>Confirmé</option><option>Annulé</option><option>Terminé</option></select></label></div></details>
 <div className="calendar-legend"><span><i className="source-manual"/>Événement manuel</span><span><i className="source-mission"/>Mission</span><span><i className="source-dossier"/>Échéance dossier</span><span><i className="source-equipment"/>Équipement voirie</span>{allItems.some((item)=>item.source==="google")&&<span><i className="source-google"/>Google Calendar</span>}</div>
 {view==="month"?<MonthGrid anchor={anchor} items={visible} onSelect={selectItem}/>:view==="week"?<WeekGrid anchor={anchor} items={visible} onSelect={selectItem}/>:<AgendaList items={visible} view={view} onSelect={selectItem}/>} {visible.length===0&&<div className="calendar-empty"><CalendarDays/><strong>Aucun événement</strong><span>Aucun résultat pour cette période et ces filtres.</span></div>}
 {selected&&<aside className="calendar-detail" aria-label="Détail de l’événement"><button className="calendar-close" onClick={()=>{setSelected(undefined);setParams({},{replace:true})}} aria-label="Fermer">×</button><span className={`calendar-source source-${selected.source}`}>{sourceLabels[selected.source]}</span><h3>{selected.title}</h3><p>{selected.description||"Aucune description."}</p><dl><div><dt>Date</dt><dd>{new Date(selected.startAt).toLocaleString("fr-FR",selected.allDay?{dateStyle:"full"}:{dateStyle:"full",timeStyle:"short"})}</dd></div><div><dt>Lieu</dt><dd>{selected.location||selected.address||"Non précisé"}</dd></div><div><dt>Statut</dt><dd>{selected.status}</dd></div><div><dt>Visibilité</dt><dd>{selected.visibility}</dd></div>{selected.externalCalendarName&&<div><dt>Agenda source</dt><dd>{selected.externalCalendarName}</dd></div>}</dl>{selected.managedExternally&&<p className="calendar-managed-notice">Géré dans Google Calendar · lecture seule dans CommunePilot</p>}{selected.dossierId&&<Link to={`/dossiers/${selected.dossierId}`}>Ouvrir le dossier lié</Link>}{selected.missionId&&<Link to={user.role==="Agent technique"?"/terrain":"/missions"}>Ouvrir la mission source</Link>}{selected.attachments.map((a)=><a key={a.id} href={a.url} target="_blank" rel="noreferrer">{a.label}</a>)}{!selected.readOnly&&<div className="calendar-detail-actions">{can("calendrier","update")&&<button className="secondary-button" onClick={()=>{setEditing(events.find((e)=>e.id===selected.id));setFormOpen(true)}}>Modifier</button>}{can("calendrier","delete")&&<button className="danger-button" onClick={()=>remove(events.find((e)=>e.id===selected.id)!)}><Trash2/> Supprimer</button>}<button className="secondary-button" onClick={()=>exportIcs([selected],`${selected.title}.ics`)}>Exporter ICS</button></div>}</aside>}
 {formOpen&&<EventForm event={editing} users={users} dossiers={dossiers} missions={missions} organizerId={user.id} initialCategory={commissionContext} onClose={()=>{setFormOpen(false);setEditing(undefined)}} onSubmit={save} onCreateDossier={can("dossiers","create")?()=>setDossierOpen(true):undefined}/>}<DossierForm isOpen={dossierOpen} initialCategory={commissionContext} onClose={()=>setDossierOpen(false)} onSubmit={createDossier}/>
 </section>;
}

function EventChip({item,onSelect}:{item:CalendarItem;onSelect(item:CalendarItem):void}){return <button className={`calendar-chip source-${item.source}`} style={{"--event-color":item.color} as React.CSSProperties} onClick={()=>onSelect(item)} title={`${formatTime(item)} · ${item.title}`}><time>{formatTime(item)}</time><span>{item.title}</span></button>}
function MonthGrid({anchor,items,onSelect}:{anchor:Date;items:CalendarItem[];onSelect(item:CalendarItem):void}){const first=periodStart(anchor,"month"),start=new Date(first);start.setDate(start.getDate()-((start.getDay()+6)%7));const days=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d});return <div className="calendar-month"><div className="calendar-weekdays">{["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"].map((d)=><span key={d}>{d}</span>)}</div><div className="calendar-month-grid">{days.map((day)=><div className={`calendar-day ${day.getMonth()!==anchor.getMonth()?"outside":""} ${dayKey(day)===dayKey(new Date())?"today":""}`} key={dayKey(day)}><span className="day-number">{day.getDate()}</span>{items.filter((i)=>itemDay(i)===dayKey(day)).slice(0,4).map((item)=><EventChip item={item} onSelect={onSelect} key={item.id}/>)}{items.filter((i)=>itemDay(i)===dayKey(day)).length>4&&<small>+ {items.filter((i)=>itemDay(i)===dayKey(day)).length-4}</small>}</div>)}</div></div>}
function WeekGrid({anchor,items,onSelect}:{anchor:Date;items:CalendarItem[];onSelect(item:CalendarItem):void}){const start=periodStart(anchor,"week");return <div className="calendar-week">{Array.from({length:7},(_,i)=>{const day=new Date(start);day.setDate(day.getDate()+i);return <section className={dayKey(day)===dayKey(new Date())?"today":""} key={dayKey(day)}><header><span>{day.toLocaleDateString("fr-FR",{weekday:"short"})}</span><strong>{day.getDate()}</strong></header><div>{items.filter((item)=>itemDay(item)===dayKey(day)).map((item)=><EventChip item={item} onSelect={onSelect} key={item.id}/>)}</div></section>})}</div>}
function AgendaList({items,view,onSelect}:{items:CalendarItem[];view:CalendarView;onSelect(item:CalendarItem):void}){const groups=[...new Set(items.map(itemDay))];return <div className={`calendar-agenda view-${view}`}>{groups.map((day)=><section key={day}><header><strong>{new Date(`${day}T12:00:00`).toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long"})}</strong></header>{items.filter((item)=>itemDay(item)===day).map((item)=><button className={`agenda-row source-${item.source}`} onClick={()=>onSelect(item)} key={item.id}><time>{formatTime(item)}</time><i style={{background:item.color}}/><div><strong>{item.title}</strong><span>{item.type} · {item.location||item.address||sourceLabels[item.source]}</span></div><em>{item.status}</em></button>)}</section>)}</div>}
